name: Build Muffle

on:
  push:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies (packages)
        run: |
          npm install -g create-dmg
          brew install graphicsmagick imagemagick

      - name: Compile
        run: make package

      - name: Upload app to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binder
          path: ${{ github.workspace }}/packages/*.dmg
